create extension if not exists pgcrypto;

create table if not exists public.feedbacks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  feedback_type text not null check (feedback_type in ('editoria_incorreta','noticia_duplicada','noticia_ausente','outro')),
  news_text text not null,
  comment text,
  status text not null default 'novo' check (status in ('novo','analisado','resolvido')),
  browser text,
  app_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  subject text not null check (subject in ('duvida','sugestao','problema_tecnico','financeiro','outro')),
  message text not null,
  status text not null default 'novo' check (status in ('novo','analisado','resolvido')),
  browser text,
  app_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('search','copy_results','copy_article','result_filter')),
  metadata jsonb not null default '{}'::jsonb,
  app_version text,
  created_at timestamptz not null default now()
);

create index if not exists feedbacks_created_at_idx on public.feedbacks(created_at desc);
create index if not exists feedbacks_status_idx on public.feedbacks(status);
create index if not exists contacts_created_at_idx on public.contacts(created_at desc);
create index if not exists contacts_status_idx on public.contacts(status);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_type_idx on public.analytics_events(event_type);
create index if not exists analytics_events_user_idx on public.analytics_events(user_id);

alter table public.feedbacks enable row level security;
alter table public.contacts enable row level security;
alter table public.analytics_events enable row level security;

revoke all on public.feedbacks from anon, authenticated;
revoke all on public.contacts from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;

grant usage on schema public to service_role;
grant all on public.feedbacks to service_role;
grant all on public.contacts to service_role;
grant all on public.analytics_events to service_role;
grant usage, select on sequence public.analytics_events_id_seq to service_role;

create or replace function public.set_admin_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists feedbacks_updated_at on public.feedbacks;
create trigger feedbacks_updated_at before update on public.feedbacks
for each row execute function public.set_admin_updated_at();

drop trigger if exists contacts_updated_at on public.contacts;
create trigger contacts_updated_at before update on public.contacts
for each row execute function public.set_admin_updated_at();
